version: "3.9"
services:
  api:
    build: ./backend
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [redis, postgres]
  worker:
    build: ./agents
    env_file: .env
    depends_on: [redis, api]
  web:
    build: ./frontend
    env_file: .env
    ports: ["3000:3000"]
  redis:
    image: redis:7
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports: ["5432:5432"]

