name: Nightly Data Pipeline

on:
  schedule:
    - cron: '0 2 * * *'     # всеки ден в 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read             # четене на кода
  actions: write             # за ръчно рестартиране/анотации (по желание)

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1) Вземи репото
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) Системни пакети (pandoc за PDF)
      - name: Install system deps (pandoc for whitepaper)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      # 4) Python зависимости
      - name: Install Python deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy boto3 prefect requests reportlab pyarrow

      # 5) Кратък дебъг (по желание)
      - name: Quick debug (env + tree)
        shell: bash
        run: |
          echo "Python:" $(python --version)
          echo "Pip:" $(pip --version)
          echo "Branch:" $(git branch --show-current)
          echo "Tree level 2:"
          ls -la
          echo "Flows:"
          ls -la flows || true
          echo "Trying to find main_flow_v2.py"
          find . -maxdepth 3 -type f -name "main_flow_v2.py" -print || true

      # 6) Стартирай pipeline v2
      - name: Run pipeline v2
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          set -e
          python flows/main_flow_v2.py

      # 7) Диагностика след изпълнение (по желание)
      - name: Post-run diagnostics
        shell: bash
        if: always()
        run: |
          echo "Disk usage:"
          df -h
          echo "Working dir:"
          pwd
          echo "List:"
          ls -la

