name: Nightly Data Pipeline

on:
  schedule:
    - cron: '0 2 * * *'   # всеки ден 02:00 UTC
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy boto3 prefect requests reportlab pyarrow

      - name: Install pandoc (for whitepaper)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      # по избор: дебъг за проверка, че файлът е на правилното място
      - name: Debug repo tree
        run: |
          pwd
          git branch --show-current
          ls -la
          echo "---- find flows ----"
          find . -maxdepth 3 -type f -name "main_flow_v2.py" -print
          echo "---- list flows dir ----"
          ls -la flows || true

      - name: Run pipeline v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python flows/main_flow_v2.py


